name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
    RELEASE: ${{ secrets.DOCKERHUB_USER }}/${{ vars.IMAGE_NAME }}

jobs:
  deploy_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [full,slim]
        include:
          - variant: full
            target: full
            tag: lates
          - variant: slim
            target: slim
            tag: slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --target ${{ matrix.target }} -t ${{ env.RELEASE }}:${{ matrix.tag }} .

      - name: Push image to Docker Hub
        run: docker push ${{ env.RELEASE }}:${{ matrix.tag }}
