name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
    IMAGE_NAME: 'ubuntu-dind'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:latest
